### PR TITLE
Medaka

### PR DESCRIPTION
**Pull request by sagrudd**
Dear Team artic-fieldbioinformatics - 
Please accept PR for some subtle fixes to the medaka branch - this corrects a couple of typos and some of the medaka code that went into the main branch has been copied here - have tested and is functional; docker container on the way! As per @cjw85 recommendations parameters included for medaka snp (--threshold 1.0) and I have dropped the broken reference to medaka-model at the consensus step.
Thanks
S

### CODE REVIEW

**Comment by nickloman** [comment]
Hi Steven - huge thanks for the assistance here!

One small thing: margin_cons_medaka script also drops het calls by inspecting the genotype field. Do you think it's important to drop them from the Medaka output here?

**Comment by cjw85** [comment]
With the `--threshold` parameter set high, het calls should come with pretty low scores (so easily filtered). In the first instance it might be useful to keep them in for debug (they might imply something nefarious in the sample)?

**Comment by nickloman** [comment]
Yes I think it is useful for looking for mixed sites - for example spotting contamination and it's something that can be reported out. So maybe we'll take that out for now?

**Comment by sagrudd** [comment]
OK - have reverted the change associated with `medaka snp` - will, as suggested, move this reduction to reporting stage

**Pull request merged**
